import { names, numbers } from "./data.js";
import { firstEle, withoutLastEle, lastEle, withoutFirstEle, filteredArray } from "./functions.js";
import { sumArray, uniqSum } from "./functions.js";
import { randomIntBetweenTwoNumbers } from "./functions.js";
import { capitalize } from "./functions.js";
import { toTitleCase } from "./functions.js";
import { allUpperCase } from "./functions.js";
import { compareLastChar } from "./functions.js";

// console.log(firstEle(names));
// console.log(firstEle(numbers));
// console.log(withoutLastEle(numbers));
// console.log(withoutLastEle(names));
// console.log(lastEle(numbers));
// console.log(lastEle(names));
// console.log(withoutFirstEle(names));
// console.log(withoutFirstEle(numbers));
// console.log(filteredArray(names, "Eric"));
// console.log(uniqSum(numbers));
// console.log(sumArray(numbers));
// console.log(randomIntBetweenTwoNumbers(5, 10));
// console.log(capitalize("iCH bIN mÜdE"));
// console.log(toTitleCase("mÜDE biN iCh"));
// console.log(allUpperCase("alle wörTer in GroßSchrift"));
// console.log(compareLastChar("Testy", "Test"));
